Mapping automation
statikbe/laravel-surveyhero pull request #6
Opened 2023-01-03 15:30 UTC by RobbeReygel

See readme + upgrade guide for more info on these changes

2023-01-04 11:40 UTC, sten requested changes
@RobbeReygel Looks very good. Kan je nog eens naar mijn comments kijken! Ik heb de readme nog wat getweakt.

2023-01-04 11:40 UTC, sten commented on src/Commands/SurveyheroMapperCommand.php
>          foreach ($surveys as $surveyIndex => $survey) {
indentation lijkt niet ok. if staat rond foreach maar op hetzelfde niveau

2023-01-04 11:40 UTC, sten commented on config/surveyhero.php
> +                        [
Zouden we die ids als key dan ook niet op subquestion niveau doortrekken voor consequent te zijn? En ook daar geen mapping conflicts te krijgen?

2023-01-04 13:01 UTC, RobbeReygel commented on src/Commands/SurveyheroMapperCommand.php
>          foreach ($surveys as $surveyIndex => $survey) {
Die if sluit zichzelf 2 lijnen verder terug, should be fine I think

2023-01-04 13:13 UTC, RobbeReygel commented on config/surveyhero.php
> +                        [
Good point @sten ! Fixed

2023-01-06 14:14 UTC, sten approved these changes

2023-01-06 14:34 UTC, merged